### ISSUE TITLE
Trying to clone down your project...

### ISSUE THREAD

**Issue by turnerniles** [dotheygandalf/disneylandWaitTimes#1]
I'm getting the error 

```
TypeError: path must be absolute or specify root to res.sendFile
   at ServerResponse.sendFile (/Users/turnerniles/src/disneylandWaitTimes/node_modules/express/lib/response.js:403:11)

```

when starting app.js. What should my root path be in my config?

```
var config = {
  port: 3000,
    mongodb: {
        url: 'mongodb://localhost:27017/disneypark'
    },
  root: ""
};

module.exports = config;

```

**Comment by dotheygandalf** [comment]
root should be set to the variable __dirname
also, if you want to record wait times, you need run your node server in production mode in order to get it to record wait times. 
NODE_ENV=testing node app.js
